version: "3"
services:
  develop:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/mnt
    stdin_open: true
    image: "spotify_slack_voting_develop"
    container_name: "spotify_slack_voting_develop_${USER}"
    tty: true
